import { Component } from '@angular/core';


function log(target:any, name:any, descriptor:any) {

  //console.log(target,name,descriptor);

  //store the original function in a varible
  const original = descriptor.value;

  //Do some manipulations with desciptor.value
  descriptor.value = function(...args){
    console.log("The arguments passed to this function are",args)
    const result = original.apply(this,args);
    console.log("The result of the function is ",result)
    return result;
  }
  //Retrun the descriptor
  return descriptor;
}
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'intro';

  constructor() {
    console.log("This statement was generated by the constructor" , this.aSimpleMethod(5,2))
  }

  @log
  aSimpleMethod(a,b){
    return a*b;
  }
}
